-- Create qr_codes table
CREATE TABLE IF NOT EXISTS public.qr_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL REFERENCES public.config_restaurantes(id) ON DELETE CASCADE,
    slug TEXT NOT NULL UNIQUE,
    total_scans INTEGER DEFAULT 0,
    papel_fundo TEXT DEFAULT 'padrao' CHECK (papel_fundo IN ('padrao', 'rustico', 'moderno')),
    ativo BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create qr_scans table
CREATE TABLE IF NOT EXISTS public.qr_scans (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    qr_code_id BIGINT NOT NULL REFERENCES public.qr_codes(id) ON DELETE CASCADE,
    scanned_at TIMESTAMPTZ DEFAULT NOW(),
    user_agent TEXT,
    ip_hash TEXT
);

-- Unique active QR code per restaurant
CREATE UNIQUE INDEX IF NOT EXISTS unique_active_qr_code_per_restaurante
ON public.qr_codes (restaurante_id)
WHERE ativo = true;

-- Enable RLS
ALTER TABLE public.qr_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qr_scans ENABLE ROW LEVEL SECURITY;

-- RLS Policies for qr_codes
DROP POLICY IF EXISTS "authenticated_select_qr_codes" ON public.qr_codes;
CREATE POLICY "authenticated_select_qr_codes" ON public.qr_codes
    FOR SELECT TO authenticated
    USING (restaurante_id = (SELECT restaurante_id FROM public.usuarios WHERE id = auth.uid() LIMIT 1));

DROP POLICY IF EXISTS "authenticated_insert_qr_codes" ON public.qr_codes;
CREATE POLICY "authenticated_insert_qr_codes" ON public.qr_codes
    FOR INSERT TO authenticated
    WITH CHECK (restaurante_id = (SELECT restaurante_id FROM public.usuarios WHERE id = auth.uid() LIMIT 1));

DROP POLICY IF EXISTS "authenticated_update_qr_codes" ON public.qr_codes;
CREATE POLICY "authenticated_update_qr_codes" ON public.qr_codes
    FOR UPDATE TO authenticated
    USING (restaurante_id = (SELECT restaurante_id FROM public.usuarios WHERE id = auth.uid() LIMIT 1))
    WITH CHECK (restaurante_id = (SELECT restaurante_id FROM public.usuarios WHERE id = auth.uid() LIMIT 1));

DROP POLICY IF EXISTS "authenticated_delete_qr_codes" ON public.qr_codes;
CREATE POLICY "authenticated_delete_qr_codes" ON public.qr_codes
    FOR DELETE TO authenticated
    USING (restaurante_id = (SELECT restaurante_id FROM public.usuarios WHERE id = auth.uid() LIMIT 1));

-- RLS Policies for qr_scans
DROP POLICY IF EXISTS "authenticated_select_qr_scans" ON public.qr_scans;
CREATE POLICY "authenticated_select_qr_scans" ON public.qr_scans
    FOR SELECT TO authenticated
    USING (
        qr_code_id IN (
            SELECT id FROM public.qr_codes 
            WHERE restaurante_id = (SELECT restaurante_id FROM public.usuarios WHERE id = auth.uid() LIMIT 1)
        )
    );

DROP POLICY IF EXISTS "allow_insert_qr_scans" ON public.qr_scans;
CREATE POLICY "allow_insert_qr_scans" ON public.qr_scans
    FOR INSERT
    WITH CHECK (true);
